telegram:
  token: 6202443309:AAHlgScZALxuR5lk9PCNl5QysaUw0VRYsbo
  webhook:
    url: https://luv06.github.io/LuvGPT
    port: 5000
  admins:
    - ren_luv
chat_gpt:
  api_key: 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
  model: GPT-3
  temperature: 0.8
  max_length: 100
  mode: roleplay
