name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker-compose --env-file config/config.env up --build -d

      - name: Set webhook URL
        run: |
          curl --location --request POST "https://api.telegram.org/6202443309:AAHlgScZALxuR5lk9PCNl5QysaUw0VRYsbo/setWebhook" \
          --form "url=https://luv06.github.io/LuvGPT"
